### ISSUE TITLE
SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by SomnusWu** [MeoMunDep/Chill-Guy-Xmas#4]
state.msecs ??= -Infinity;
                ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)

**Comment by MeoMunDep** [comment]
screenshot

**Comment by SomnusWu** [comment]
![0241218160555](https://github.com/user-attachments/assets/d7bae7b8-6b4a-403f-85ea-7a5884efee8f)

**Comment by SomnusWu** [comment]
I obtained users.txt using “Telegram Mini App Auth Extractor”。
![image](https://github.com/user-attachments/assets/11f1831a-d227-4db2-9bf1-bedc987c3491)

**Comment by MeoMunDep** [comment]
just use my extension, dont do anything else, keep following the guides, dont waste my time

**Comment by SomnusWu** [comment]
sorry ,I used your tool to get the query_id, but it still has the same error.
![506feb4ad60fd191a2d9b1271b15a86](https://github.com/user-attachments/assets/dcdb5892-6aff-4393-97c8-1896a4fe3010)

**Comment by MeoMunDep** [comment]
hmm kinda weird, i still can run it, did u dowload the lastest file

**Comment by MeoMunDep** [comment]
lemme check
